# frozen_string_literal: true

source 'https://rubygems.org'

ruby '~> 3.1.0'

gem 'rabbitmq_http_api_client', '>= 2.0.0'
gem 'ruby-graphviz', '>= 1.0.0'

group :development do
  gem 'pry'
  gem 'rubocop'
end
